const {buildData} = require('../src/main')

// Validate the buildData function
function testBuildData(testEntries) {
  console.log("testBuildData starting")
  const results = buildData(testEntries)
  const check1 = (JSON.stringify(results[0]) == JSON.stringify(row_1)) ? "OK" : "FAILED"
  const check2 = (JSON.stringify(results[4]) == JSON.stringify(row_2)) ? "OK" : "FAILED"
  console.log( `buildData record 1: ${check1}` )
  console.log( `buildData record 5: ${check2}` )
}

const row_1 = {
  Handle: '10602',
  Title: 'Barney The Security Officer Character',
  'Body (HTML)': 'Barney Stands 6" Tall Dressed As A Officer With Real Security Guard Uniform Barneys Ridged Urethane Foam Torso Continuously Shakes And His Head Bobs. He Holds A Gun In One Hand And Real Handcuffs In The Other. Barney Also Comes Metal Badge Holster And Handcuff Case Clipped To His Belt.Free Freight, Continental US only. SPECIAL ORDER NO RETURNS',
  'Variant SKU': 'Barney',
  Vendor: 'Reedyville Goods',
  'Standardized Product Type': 'Home & Garden > Decor > Decorative Plaques',
  'Custom Product Type': 'Metal Sign',
  Tags: 'Barney The Security Officer Character, dolls life like, life like dolls for adults, life size dolls, very realistic looking dolls, Uncategorized',
  Published: 'TRUE',
  'Option1 Name': 'Title',
  'Option1 Value': 'Default Title',
  'Option2 Name': '',
  'Option2 Value': '',
  'Option3 Name': '',
  'Option3 Value': '',
  'Variant Grams': '0.0',
  'Weight (lbs)': '',
  'Variant Inventory Tracker': '',
  'Variant Inventory Qty': '',
  'Variant Inventory Policy': 'deny',
  'Variant Fulfillment Service': 'manual',
  'Variant Price': '',
  'Variant Compare At Price': '',
  'Variant Requires Shipping': 'TRUE',
  'Variant Taxable': 'TRUE',
  'Variant Barcode': '',
  'Image Src': 'https://reedyvillegoods.com/wp-content/uploads/2015/05/Barney.jpg',
  'Image Position': '1',
  'Image Alt Text': '',
  'Gift Card': 'FALSE',
  'SEO Title': '',
  'SEO Description': '',
  'Google Shopping / Google Product Category': '',
  'Google Shopping / Gender': '',
  'Google Shopping / Age Group': '',
  'Google Shopping / MPN': '',
  'Google Shopping / AdWords Grouping': '',
  'Google Shopping / AdWords Labels': '',
  'Google Shopping / Condition': '',
  'Google Shopping / Custom Product': '',
  'Google Shopping / Custom Label 0': '',
  'Google Shopping / Custom Label 1': '',
  'Google Shopping / Custom Label 2': '',
  'Google Shopping / Custom Label 3': '',
  'Google Shopping / Custom Label 4': '',
  'Variant Image': '',
  'Variant Weight Unit': 'lbs',
  'Variant Tax Code': '',
  'Cost per item': '',
  'Price / International': '',
  'Compare At Price / International': '',
  Status: 'active',
  '': '',
  'Reedyville Price': '998',
  'Wholesale Rate (50%)': '499',
  Shipping: '35',
  'Sale Price (Formula)': '1033',
  'WordPress Type': 'simple',
  'WordPress Length (in)': '',
  'WordPress Width (in)': '',
  'WordPress Height (in)': '6',
  'WordPress Tags': 'Barney The Security Officer Character, dolls life like, life like dolls for adults, life size dolls, very realistic looking dolls',
  'WordPress Categories': 'Uncategorized',
  'WordPress Images': 'https://reedyvillegoods.com/wp-content/uploads/2015/05/Barney.jpg',
  'WordPress Parent': '',
  'WordPress Grouped products': ''
}

const row_2 = {
  Handle: '55399',
  Title: 'Great Minds Drink Wine Metal Sign Gives The Illusion Of Real Copper NOT  COPPER. 19x24',
  'Body (HTML)': 'Great Minds Drink Wine Laser Cut Metal Sign.  This Picture Is A Representation Of The Original Product. This is a Unique One Of A Kind Process. No Two Are Alike. 19"x24" 16 Gauge Steel. Made In The USA. CA202',
  'Variant SKU': 'CA202',
  Vendor: 'Reedyville Goods',
  'Standardized Product Type': 'Home & Garden > Decor > Decorative Plaques',
  'Custom Product Type': 'Metal Sign',
  Tags: '16g Steel, 19"x24", Bar, Copper, metal, Restaurant, Sign, Wall Art, Wall D?cor, Wall Hanging, Wine, Copper Accents Wall D?cor, Copper Accents Wall Décor > Copper Illusions',
  Published: 'TRUE',
  'Option1 Name': 'Title',
  'Option1 Value': 'Default Title',
  'Option2 Name': '',
  'Option2 Value': '',
  'Option3 Name': '',
  'Option3 Value': '',
  'Variant Grams': '198.4',
  'Weight (lbs)': '7',
  'Variant Inventory Tracker': '',
  'Variant Inventory Qty': '',
  'Variant Inventory Policy': 'deny',
  'Variant Fulfillment Service': 'manual',
  'Variant Price': '',
  'Variant Compare At Price': '',
  'Variant Requires Shipping': 'TRUE',
  'Variant Taxable': 'TRUE',
  'Variant Barcode': '',
  'Image Src': 'https://reedyvillegoods.com/wp-content/uploads/2019/04/CA202-1.jpg',
  'Image Position': '1',
  'Image Alt Text': '',
  'Gift Card': 'FALSE',
  'SEO Title': '',
  'SEO Description': '',
  'Google Shopping / Google Product Category': '',
  'Google Shopping / Gender': '',
  'Google Shopping / Age Group': '',
  'Google Shopping / MPN': '',
  'Google Shopping / AdWords Grouping': '',
  'Google Shopping / AdWords Labels': '',
  'Google Shopping / Condition': '',
  'Google Shopping / Custom Product': '',
  'Google Shopping / Custom Label 0': '',
  'Google Shopping / Custom Label 1': '',
  'Google Shopping / Custom Label 2': '',
  'Google Shopping / Custom Label 3': '',
  'Google Shopping / Custom Label 4': '',
  'Variant Image': '',
  'Variant Weight Unit': 'lbs',
  'Variant Tax Code': '',
  'Cost per item': '',
  'Price / International': '',
  'Compare At Price / International': '',
  Status: 'active',
  '': '',
  'Reedyville Price': '40',
  'Wholesale Rate (50%)': '',
  Shipping: '13',
  'Sale Price (Formula)': '13',
  'WordPress Type': 'simple',
  'WordPress Length (in)': '25',
  'WordPress Width (in)': '21',
  'WordPress Height (in)': '5',
  'WordPress Tags': '16g Steel, 19"x24", Bar, Copper, metal, Restaurant, Sign, Wall Art, Wall D?cor, Wall Hanging, Wine',
  'WordPress Categories': 'Copper Accents Wall D?cor, Copper Accents Wall Décor > Copper Illusions',
  'WordPress Images': 'https://reedyvillegoods.com/wp-content/uploads/2019/04/CA202-1.jpg',
  'WordPress Parent': '',
  'WordPress Grouped products': ''
}

module.exports = {testBuildData}